const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');
if(toggle&&nav){toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.setAttribute('aria-label',open?'Ouvrir le menu':'Fermer le menu');nav.classList.toggle('is-open',!open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Ouvrir le menu');nav.classList.remove('is-open')}))}
const items=document.querySelectorAll('.mission-card,.info-card,.journey-grid article,.intervention-grid article,.equipment-card,.grade-grid article,.pathway-grid article');
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});items.forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
document.querySelector('#year').textContent=new Date().getFullYear();
const questions=[
{question:'Quel numéro appeler en France pour joindre les sapeurs-pompiers ?',answers:['15','17','18','119'],correct:2,explanation:'Le 18 permet de joindre les sapeurs-pompiers. Le 112 est également le numéro d’urgence européen.'},
{question:'Que signifie le sigle VSAV ?',answers:['Véhicule de secours et d’assistance aux victimes','Véhicule de surveillance et d’alerte volontaire','Véhicule spécialisé d’appui aux volontaires'],correct:0,explanation:'VSAV signifie véhicule de secours et d’assistance aux victimes.'},
{question:'Quel équipement aide un pompier à respirer dans un milieu enfumé ?',answers:['Un gilet haute visibilité','Un appareil respiratoire isolant','Un détecteur thermique'],correct:1,explanation:'L’ARI (appareil respiratoire isolant) fournit de l’air respirable.'},
{question:'Que faire en premier en découvrant un accident ?',answers:['Déplacer immédiatement les victimes','Se protéger, sécuriser les lieux et alerter les secours','Filmer la scène'],correct:1,explanation:'Protéger, alerter et secourir : la protection et l’alerte font partie des premiers réflexes.'},
{question:'À quoi sert principalement un fourgon pompe-tonne (FPT) ?',answers:['À éteindre les incendies','À transporter des victimes','À déployer une grande échelle'],correct:0,explanation:'Le FPT est un véhicule de lutte contre l’incendie, doté notamment d’une pompe et d’une réserve d’eau.'}];
let current=0,score=0,locked=false;const q=document.querySelector('#quiz-question'),answers=document.querySelector('#quiz-answers'),feedback=document.querySelector('#quiz-feedback'),next=document.querySelector('#quiz-next'),scoreNode=document.querySelector('#quiz-score'),progress=document.querySelector('#quiz-progress'),bar=document.querySelector('#quiz-progress-bar'),box=document.querySelector('#quiz-box'),result=document.querySelector('#quiz-result');
function render(){locked=false;const item=questions[current];q.textContent=item.question;progress.textContent=`QUESTION ${String(current+1).padStart(2,'0')} / ${String(questions.length).padStart(2,'0')}`;bar.style.width=`${current/questions.length*100}%`;feedback.textContent='';next.hidden=true;answers.replaceChildren(...item.answers.map((answer,index)=>{const button=document.createElement('button');button.type='button';button.className='quiz-answer';button.textContent=answer;button.addEventListener('click',()=>choose(index));return button}))}
function choose(index){if(locked)return;locked=true;const item=questions[current],buttons=[...answers.querySelectorAll('button')];buttons.forEach((button,i)=>{button.disabled=true;if(i===item.correct)button.classList.add('correct');else if(i===index)button.classList.add('incorrect')});const right=index===item.correct;if(right)score++;scoreNode.textContent=String(score);feedback.textContent=`${right?'Bonne réponse !':'Pas tout à fait.'} ${item.explanation}`;next.textContent=current===questions.length-1?'Voir mon résultat →':'Question suivante →';next.hidden=false;bar.style.width=`${(current+1)/questions.length*100}%`}
next.addEventListener('click',()=>{current++;if(current<questions.length){render();return}box.hidden=true;result.hidden=false;document.querySelector('#quiz-result-title').textContent=score===questions.length?'Sans faute !':score>=3?'Bravo !':'Bien joué !';document.querySelector('#quiz-result-text').textContent=`Vous avez obtenu ${score} bonne${score>1?'s':''} réponse${score>1?'s':''} sur ${questions.length}. ${score<3?'Continuez à explorer le site pour en apprendre davantage.':'Vous connaissez déjà bien l’univers des sapeurs-pompiers.'}`});
document.querySelector('#quiz-restart').addEventListener('click',()=>{current=0;score=0;scoreNode.textContent='0';result.hidden=true;box.hidden=false;render()});render();

// Filtrage de la galerie de véhicules par type de mission.
const vehicleFilters=document.querySelectorAll('.vehicle-filter');
const vehicleCards=document.querySelectorAll('.equipment-card[data-mission]');
vehicleFilters.forEach(button=>button.addEventListener('click',()=>{
  const filter=button.dataset.filter;
  vehicleFilters.forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});
  vehicleCards.forEach(card=>{card.hidden=filter!=='all'&&card.dataset.mission!==filter});
}));
